oe-core-dl-4-3.xml: add sub git repo for ovmf
Issue: LINCD-12705

github.com.google.wycheproof is not listed in .gitmodules and cause
following fetch failure, so handle it manually.

  ERROR: ovmf-edk2-stable202302-r0 do_fetch: Bitbake Fetcher Error:
  NetworkAccess('gitsm://github.com/google/wycheproof;protocol=https;name=wycheproof;subpath=wycheproof;nobranch=1;bareclone=1;nobranch=1',
  'LANG=C git -c gc.autoDetach=false -c core.pager=cat clone --bare --mirror https://github.com/google/wycheproof
  /path_to/downloads/git2/github.com.google.wycheproof --progress')

Signed-off-by: Kai Kang <kai.kang@windriver.com>